server:
  port: 8821

spring:
  thymeleaf:
    prefix:
      classpath: /templates

  datasource:
    url: jdbc:mysql://localhost:3306/db_juhe?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis:
  type-aliases-package: com.km.kmdemo.model
  mapper-locations: classpath:mapper/*.xml


